name: CD Develop

run-name: Deploy Develop

on:
    workflow_dispatch:

    push:
        branches: [ "develop" ]

    pull_request:
        branches: [ "develop" ]

jobs:
  deploy:
        name: Deploy on ${{ vars.DEVELOP_HOST }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Access server
              uses: appleboy/ssh-action@master
              with:
                host: ${{ vars.DEVELOP_HOST }}
                username: ${{ vars.DEVELOP_USERNAME }}
                port: ${{ vars.DEVELOP_PORT }}
                key: ${{ secrets.DEVELOP_SSHKEY }}
                script: |
                    cd ${{ vars.DEVELOP_BASEPATH }}
                    . .github/scripts/php.sh ${{ vars.DEVELOP_MIN_PHP_VERSION }}
                    . .github/scripts/composer.sh ${{ vars.DEVELOP_COMPOSER }}
                    . .github/scripts/deploy.sh
